Main:
  Auto Save Interval In Seconds: 15
  Heads Free In Creative Mode: false
  Drop Mob Heads: true
  Drop Player Heads: true
  Head Drop Chance: 25%

Economy:
  Economy: Vault
  Head Cost: 24.99
  Item:
    Type: PLAYER_HEAD
    Head ID: 14395
    Name: '&6Player Head Token'
    Lore:
      - '&8Use in /Heads!'

System:
  Language Mode: en_US

Interfaces:
  Glass Type 1: GRAY_STAINED_GLASS_PANE
  Glass Type 2: BLUE_STAINED_GLASS_PANE
  Glass Type 3: LIGHT_BLUE_STAINED_GLASS_PANE
