package com.songoda.epicheads.listeners;

import com.songoda.epicheads.EpicHeads;
import com.songoda.epicheads.head.Head;
import com.songoda.epicheads.utils.ItemEconomy;
import com.songoda.epicheads.utils.SkullUtils;
import org.bukkit.Material;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockPlaceEvent;
import org.bukkit.event.entity.ItemSpawnEvent;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

import java.util.ArrayList;
import java.util.Optional;

public class ItemListeners implements Listener {
    private final EpicHeads plugin;

    public ItemListeners(EpicHeads plugin) {
        this.plugin = plugin;
    }

    @EventHandler(ignoreCancelled = true, priority = EventPriority.LOWEST)
    public void itemSpawnEvent(ItemSpawnEvent event) {
        ItemStack item = event.getEntity().getItemStack();
        if (item.getType() != Material.PLAYER_HEAD
                || item.getItemMeta() != null && item.getItemMeta().hasDisplayName()) {
            return;
        }

        String encodedStr = SkullUtils.getProfileValue(item);
        if (encodedStr == null) {
            return;
        }

        String url = SkullUtils.getDecodedTexture(encodedStr);
        if (url == null) {
            return; // If reached, the head was generated by another incompatible plugin.
        }
        Optional<Head> optional = this.plugin.getHeadManager()
                .getHeads()
                .stream()
                .filter(head -> url.equals(head.getUrl()))
                .findFirst();

        if (optional.isPresent()) {
            ItemStack itemNew = optional.get().asItemStack();

            ItemMeta meta = itemNew.getItemMeta();
            meta.setLore(new ArrayList<>());
            item.setItemMeta(meta);
        }
    }

    @EventHandler
    public void onPlace(BlockPlaceEvent event) {
        if (ItemEconomy.isItem(event.getItemInHand())) {
            event.setCancelled(true);
        }
    }
}
